mod "boxen",       "3.1.0", :github_tarball => "boxen/puppet-boxen"
mod "module_data", "0.0.1", :github_tarball => "ripienaar/puppet-module-data"
mod "repository",  "2.2.0", :github_tarball => "boxen/puppet-repository"
mod "stdlib",      "4.0.0", :github_tarball => "puppetlabs/puppetlabs-stdlib"
